### ISSUE TITLE
徳山:atkadaiの質問について2

### ISSUE THREAD

**Issue by wataconda** [mtsug1/atkadai#1]
お世話になっております徳山です。
課題について、再び問題が生じたので質問させて頂きたいです。
今回の質問は技術的な質問、gitについての質問、testについての質問が一つずつあります。
長くなってしまいましたが、今回も読んで貰えると幸いです。

まず技術的な問題について、index.tsxのhandleRemove(Toastを削除する)のToastの指定についての質問です。
ToastのhandleCloseを非同期にしたところ、index.tsx内のhandleRemoveに返ってくるindex, textはToast作成時のパラメタのままなので、二つ続けてToastを作成したり、CloseボタンでToastを消したりすると順番がズレて、indexが信用できなくなってしまいます。
どうしても解決策が思いつかなかったので、質問させて頂きました。簡単なヒントでも、出して頂けると助かります。
添付されているatkadai_src.zip内のsrc/index.tsxの冒頭のコメントアウトに、試したことが書かれてあります。
[atkadai_src.zip](https://github.com/mtsug1/atkadai/files/534045/atkadai_src.zip)

次にgitについて、ヒントに従ってブランチ:questionを分けてpushしたのですが、上手くいきません。
エラーは以下のようになってしまいます。
git -c diff.mnemonicprefix=false -c core.quotepath=false push -v --tags --set-upstream origin question:question
remote: Permission to mtsug1/atkadai.git denied to tkymwtr.

fatal: unable to access 'https://tkymwtr@github.com/mtsug1/atkadai.git/': The requested URL returned error: 403
Pushing to https://tkymwtr@github.com/mtsug1/atkadai.git
これに関してインターネットにヒントが沢山あったのですが、ある程度試しても上手くいかなかったので、質問させて頂きました。sshではkeyを作りましたが、認証に失敗してしまいます。
元々bitbucketを利用していまして、gitとの接続先としてgitのアカウントを作ったのですが、もしかすると原因に関係しているかもしれません。
もし原因にお心当たりがありましたら、お教えください。

最後に、testについての質問です。testについてコードカバレッジを測るとのことなのですが、chaiを用いた方が良いでしょうか？

以上です。二度目の質問で恐縮なのですが、よろしくお願い致します。

**Comment by mtsug1** [comment]
お返事遅くなり申し訳ありません。
indexは信用しないでtextからindexOfで探す方法で十分です。
また、this.button_disabledはstateの中に入れてください。
先ほど、Collaboratorsに招待しましたので、承認くださるとpushできるようになります。
お手数をおかけしました。
テストに関しては、chaiを用いても構いません。
コードカバレッジを測ると言いましたが、ソースチェックする程度で厳密に測定するつもりはありませんので、testディレクトリ内に作成したComponentのテストを自由に書いて下さって結構です。

以上簡単ですが、よろしくお願い致します。

**Comment by wtcttn** [comment]
@tkymwtr 

お返事遅くなり申し訳ありません。
indexは信用しないでtextからindexOfで探す方法で十分です。
また、this.button_disabledはstateの中に入れてください。
先ほど、Collaboratorsに招待しましたので、承認くださるとpushできるようになります。
お手数をおかけしました。
テストに関しては、chaiを用いても構いません。
コードカバレッジを測ると言いましたが、ソースチェックする程度で厳密に測定するつもりはありませんので、testディレクトリ内に作成したComponentのテストを自由に書いて下さって結構です。

以上簡単ですが、よろしくお願い致します。

**Comment by wataconda** [comment]
御返答を確認致しました。
技術的な問題について、indexは信用しないでtextからindexOfで探す方法をとります。
gitの問題について、先ほどpushに成功しました。解決しました。
テストの質問について、test/Componentのテスト内容を書くことについて了解です。

二度目の御返答、本当にありがとうございました。期限が近くなりましたが、間に合わせるよう頑張ります。
