### ISSUE TITLE
徳山:atkadaiの質問について3

### ISSUE THREAD

**Issue by wataconda** [mtsug1/atkadai#2]
お世話になっております、徳山です。
課題としては完了したのですが、原因が分からず仕舞いの問題が発生してしまいました。

testのcomponentを作成している際、Toast.spec.tsxに元々あるtest文'Should call onRequestClose callback on 3 seconds after the mount'はToast.tsx内の3秒間をsinon.useFakeTimers()で進めて、onRequestCloseの呼び出しの有無を確かめるという内容でしたが、改変後のToast.tsxではどうしても通すことが出来ませんでした。
改変前は通すことが出来ました。

結局はuseFakeTimersを使わずに、test側でsetTimeoutを使うことでpassすることが出来ましたが、原因が分かりませんでした。
onRequestCloseが実行されるまでの時間を測ってみましたが、問題はありませんでした。
恐らく、Node.Timerを使っていないことか、非同期であることが原因であると考えていますが、もしこの問題の原因に心当たりがありましたら、お教え頂けると嬉しいです。

**Comment by mtsug1** [comment]
promiseを使用してるので、sinonが上手く機能してませんね。
promiseを使用する必要があれば、
https://github.com/bendrucker/sinon-as-promised
あたりを用いる必要がありますね。
見たところ、promiseつかう意味がなさそうにみえますが、

**Comment by wtcttn** [comment]
@tkymwtr 
お返事遅くなり申し訳ありません。
promiseを使用してるので、sinonが上手く機能してませんね。
promiseを使用する必要があれば、
https://github.com/bendrucker/sinon-as-promised
あたりを用いる必要がありますね。
見たところ、promiseつかう意味がなさそうにみえますが、

**Comment by wataconda** [comment]
お返事ありがとうございます。

質問を繰り返してしまい大変恐縮なのですが、教えて頂いたsinon-as-promisedなど、追加モジュールを有効化する為にはどのようにすればよいか、教えて頂けないでしょうか？
インストールしたモジュールはnode_moduleに入っているのですが、importするにもモジュールが見つからず、requireで実行しようにも
Warning: Could not find any test files matching pattern:
のようなエラーが出てしまいます。環境変数NODE_PATHは設定してあります。
installの際にグローバルを指定しても、--save-devでも解決しませんでした。

https://github.com/PanayotCankov/mocha-typescript/issues/9
上記のリンクにある質問にヒントがあると考えましたが、具体的に何をすればよいのか良く分かりませんでした。mochaのサーバテストだけ試してみましたが、結果は同じでした。
よろしくお願い致します。

promiseの実装について、例としてaとaaを連続して入力する場合を考えますと、setTimeoutのみの場合aの待ち時間中にaaの情報が上書きされてしまいました。これではaを消す命令が消えてしまうので、promiseを実装しました。
ただ、これが原因で他の部分に影響が出てしまうようなら、使うべきでは無かったのかも知れません。

**Comment by wtcttn** [comment]
追加モジュールを有効化する為にはtypingsから型定義を落としてくる必要がありますね。
もし型定義が存在しなければ、自分で書かなければなりません。
declare namespace SinonAsPromised {
... 省略
}
declare module "sinon-as-promised" {
      export = SinonAsPromised
}
今回の場合は、
テストファイルの先頭に
require('sinon-as-promised');
を追記するだけでいけるような気がしますが、とりあえず今回は試さなくて結構です。

ひとまず課題を受領しました。
また改めて連絡させていただきます。
お疲れ様でした。

**Comment by wataconda** [comment]
お返事ありがとうございます。

typingsの件について、了解です。
課題中でもわからないことだったので、助かりました。

課題について、提出が遅れてしまい申し訳ございませんでした。
宜しくお願い致します。

お疲れ様でした。
